/**
 * Core WPS tool set — AUTO-GENERATED by scripts/generate-core-tools.mjs.
 * Source: the official WPS SkillHub MCP `tools/list` snapshot
 * (https://mcp-center.wps.cn/skill_hub/mcp).
 *
 * Each entry's `parameters` is a sanitized raw JSON Schema (enforced subset:
 * type/properties/required/additionalProperties/items/enum/const + annotations).
 * Do not hand-edit; regenerate after refreshing the snapshot.
 */

export interface CoreToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

export const coreTools: CoreToolDefinition[] = [
  {
    "name": "list_my_files",
    "description": "列出「我的云文档」根目录子项。按关键词找文件用 search_files；已知子目录 ID 用 list_files。",
    "parameters": {
      "type": "object",
      "properties": {
        "filter_exts": {
          "description": "扩展名过滤，逗号分隔小写",
          "type": "string"
        },
        "filter_type": {
          "description": "按类型筛选",
          "type": "object",
          "properties": {
            "type": {
              "description": "file / folder / shortcut",
              "type": "string"
            }
          }
        },
        "order": {
          "description": "desc / asc",
          "type": "string"
        },
        "order_by": {
          "description": "ctime / mtime / dtime / fname / fsize",
          "type": "string"
        },
        "page_size": {
          "description": "分页大小，常用 50，限制在 1–500；超过 500 按 500；小于 1 时按 50",
          "type": "number"
        },
        "page_token": {
          "description": "分页 token",
          "type": "string"
        },
        "with_ext_attrs": {
          "description": "是否返回扩展属性",
          "type": "boolean"
        },
        "with_permission": {
          "description": "是否返回操作权限",
          "type": "boolean"
        }
      }
    }
  },
  {
    "name": "list_files",
    "description": "列出已知 drive_id 与 parent_id 的目录子项。不知道目录 ID 时：浏览个人云文档根目录用 list_my_files；按关键词找文件用 search_files。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "驱动盘 ID",
          "type": "string"
        },
        "filter_exts": {
          "description": "扩展名过滤，逗号分隔小写",
          "type": "string"
        },
        "filter_type": {
          "description": "按类型筛选",
          "type": "object",
          "properties": {
            "type": {
              "description": "file / folder / shortcut",
              "type": "string"
            }
          }
        },
        "order": {
          "description": "desc / asc",
          "type": "string"
        },
        "order_by": {
          "description": "ctime / mtime / dtime / fname / fsize",
          "type": "string"
        },
        "page_size": {
          "description": "分页大小，常用 50，限制在 1–500；超过 500 按 500；小于 1 时按 50",
          "type": "number"
        },
        "page_token": {
          "description": "分页 token",
          "type": "string"
        },
        "parent_id": {
          "description": "文件夹 ID，根目录为 \"0\"",
          "type": "string"
        },
        "with_ext_attrs": {
          "description": "是否返回扩展属性",
          "type": "boolean"
        },
        "with_permission": {
          "description": "是否返回操作权限",
          "type": "boolean"
        }
      },
      "required": [
        "drive_id",
        "parent_id"
      ]
    }
  },
  {
    "name": "search_files",
    "description": "按关键词跨盘/跨目录搜索云文档（文件/文件夹）；支持文件名、内容或全局检索（type 默认 all）。仅要文件夹或文件时用 file_type，勿将 folder/file 填入 type。已知目录 ID 浏览子项用 list_files；无 ID 浏览个人云文档根目录用 list_my_files。",
    "parameters": {
      "type": "object",
      "properties": {
        "channels": {
          "description": "渠道",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "creator_ids": {
          "description": "创建者 ID",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "device_ids": {
          "description": "设备 ID",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "drive_ids": {
          "description": "搜索盘列表",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "end_time": {
          "description": "最大时间",
          "type": "number"
        },
        "exclude_channels": {
          "description": "排除渠道",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exclude_file_exts": {
          "description": "排除后缀",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file_ext_groups": {
          "description": "文件分组后缀",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file_exts": {
          "description": "文件后缀",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file_type": {
          "description": "folder / file / shortcut",
          "type": "string"
        },
        "filter_user_id": {
          "description": "创建者分享者过滤",
          "type": "number"
        },
        "keyword": {
          "description": "搜索关键字",
          "type": "string"
        },
        "modifier_ids": {
          "description": "编辑者 ID",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "order": {
          "description": "desc / asc",
          "type": "string"
        },
        "order_by": {
          "description": "ctime / mtime",
          "type": "string"
        },
        "page_size": {
          "description": "分页大小，常用 50；传 0 表示按 50；限制在 0–500；超过 500 按 500",
          "type": "number"
        },
        "page_token": {
          "description": "翻页 token",
          "type": "string"
        },
        "parent_ids": {
          "description": "搜索目录",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "receiver_ids": {
          "description": "接收者 ID",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "scope": {
          "description": "搜索范围 all/share_by_me/...",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "search_operator_name": {
          "description": "是否搜创建者或分享者名",
          "type": "boolean"
        },
        "sharer_ids": {
          "description": "分享者 ID",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "start_time": {
          "description": "最小时间",
          "type": "number"
        },
        "time_type": {
          "description": "ctime / mtime / otime / stime",
          "type": "string"
        },
        "type": {
          "description": "搜索维度，默认 all。仅支持 file_name / content / all；筛选文件夹/文件请用 file_type",
          "type": "string",
          "enum": [
            "file_name",
            "content",
            "all"
          ]
        },
        "with_drive": {
          "description": "是否返回驱动盘",
          "type": "boolean"
        },
        "with_link": {
          "description": "是否返回分享信息",
          "type": "boolean"
        },
        "with_permission": {
          "description": "是否返回操作权限",
          "type": "boolean"
        },
        "with_total": {
          "description": "是否返回总条数",
          "type": "boolean"
        }
      }
    }
  },
  {
    "name": "get_file_info",
    "description": "获取文件（夹）信息。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件（夹） id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "with_drive": {
          "description": "是否返回文件所属 drive 信息",
          "type": "boolean"
        },
        "with_ext_attrs": {
          "description": "是否返回文件扩展属性",
          "type": "boolean"
        },
        "with_permission": {
          "description": "是否返回文件操作权限",
          "type": "boolean"
        }
      }
    }
  },
  {
    "name": "create_file_with_content",
    "description": "新建并写入内容：先看 name 后缀或 file_extension，再只传该后缀所需字段。\n- .otl/.docx → content（Markdown 明文 UTF-8）；缺省时创建空白文档（action=created_empty）\n- .pdf → 须传 content（Markdown 转档）；无 content 不降级，可改 upload_new_file\n- .xls/.xlsx/.ksheet → rangeData（单元格数据）\n- .dbt → records + fields\n不支持 .ppt/.pptx/.csv。只要空白文档也可用 create_empty_file。",
    "parameters": {
      "type": "object",
      "properties": {
        "content": {
          "description": "仅文本族必填（otl/docx/pdf）。Markdown 正文（UTF-8 明文，非 Base64）",
          "type": "string"
        },
        "drive_id": {
          "description": "可选。目标云盘 ID；不传时自动使用默认个人盘",
          "type": "string"
        },
        "fields": {
          "description": "仅 dbt 必填。列定义数组；每项需包含 name 与 type",
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "file_extension": {
          "description": "文档扩展名：otl/docx/pdf/xls/xlsx/ksheet/dbt",
          "type": "string"
        },
        "name": {
          "description": "文件名，如 `周报.otl`",
          "type": "string"
        },
        "parent_id": {
          "description": "可选。父文件夹 ID；不传默认根目录 \"0\"",
          "type": "string"
        },
        "rangeData": {
          "description": "仅表格族必填（xls/xlsx/ksheet）。单元格数据数组；每项含 row_from/row_to/col_from/col_to/formula",
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "records": {
          "description": "仅 dbt 必填。记录数组；每项须含 fields 对象",
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "sheet_name": {
          "description": "可选。目标工作表/数据表名称；不传时自动新建「新数据表」",
          "type": "string"
        }
      },
      "required": [
        "name",
        "file_extension"
      ]
    }
  },
  {
    "name": "create_folder",
    "description": "新建文件夹。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "驱动盘 ID",
          "type": "string"
        },
        "name": {
          "description": "文件夹名称，无需后缀",
          "type": "string"
        },
        "on_name_conflict": {
          "description": "fail / rename，默认 rename",
          "type": "string"
        },
        "parent_id": {
          "description": "父文件夹 ID，根目录为 \"0\"",
          "type": "string"
        },
        "parent_path": {
          "description": "相对路径，不存在则自动创建",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "drive_id",
        "parent_id",
        "name"
      ]
    }
  },
  {
    "name": "upload_new_file",
    "description": "上传本地文件新建云文档，须传 content_base64。对话内直接撰写内容请使用 create_file_with_content。",
    "parameters": {
      "type": "object",
      "properties": {
        "content_base64": {
          "description": "本地文件内容 Base64。若为 Markdown：请先确保内容编码格式为 UTF-8，再对原始文本做 Base64 编码后传入",
          "type": "string"
        },
        "content_format": {
          "description": "可选：源内容格式。支持 doc / docx / xls / xlsx / ppt / pptx / pdf / md / txt / html / zip / png / jpg / jpeg / csv / json / dps / et / wps / gif；其中 markdown 仅支持转为 docx / pdf 后上传",
          "type": "string",
          "enum": [
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "pdf",
            "md",
            "txt",
            "html",
            "zip",
            "png",
            "jpg",
            "jpeg",
            "csv",
            "json",
            "dps",
            "et",
            "wps",
            "gif",
            "markdown"
          ]
        },
        "drive_id": {
          "description": "云盘 ID。未传时服务端自动取默认个人云盘",
          "type": "string"
        },
        "file_sum": {
          "description": "可选：文件哈希值，与 file_type 同传时转成 hashes；不传则服务端按内容计算",
          "type": "string"
        },
        "file_type": {
          "description": "可选：哈希类型，支持类型包括：sha256 / md5 / sha1",
          "type": "string",
          "enum": [
            "sha256",
            "md5",
            "sha1"
          ]
        },
        "name": {
          "description": "文件名，须带后缀，如 .docx / .md；支持 doc / docx / xls / xlsx / ppt / pptx / pdf / md / txt / html / zip / png / jpg / jpeg / csv / json / dps / et / wps / gif",
          "type": "string"
        },
        "parent_id": {
          "description": "父文件夹 ID，根目录为 \"0\"。未传时默认 \"0\"",
          "type": "string"
        },
        "parent_path": {
          "description": "父文件夹路径分段（文件夹名，非 ID）。新建时按文件夹名指定父路径",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "content_base64"
      ]
    }
  },
  {
    "name": "download_file",
    "description": "获取文件下载信息。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "驱动盘 ID",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "internal": {
          "description": "是否内网下载地址",
          "type": "boolean"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "storage_base_domain": {
          "description": "wps.cn / kdocs.cn / wps365.com",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "with_hash": {
          "description": "是否返回校验值 hashes",
          "type": "boolean"
        }
      }
    }
  },
  {
    "name": "read_file",
    "description": "读取云文档正文，按文件格式自动返回 Markdown 或结构化数据：url、link_id、file_id 至少填一个；多填时取 url > link_id > file_id。支持 docx / pdf / xlsx / otl / ppt / pptx 等；docx/pdf 默认返回 markdown；ppt/pptx 默认返回 kdc，可传 format=markdown 获取 Markdown；xlsx/xls 默认读取表格选区，可传 format=markdown 整文件抽取。不支持 CSV 与未识别类型。",
    "parameters": {
      "type": "object",
      "properties": {
        "enable_upload_medias": {
          "description": "是否将文档中的多媒体附件上传对象存储，默认 false；为 true 时抽取结果中附件会返回有效期内可下载的 URL。doc/docx/wps/pdf/otl/ppt/pptx 且 format=markdown 或 kdc，以及 xlsx/xls 且 format=markdown 时生效",
          "type": "boolean"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "format": {
          "description": "文档内容目标格式。可选值：`markdown` / `plain`（纯文本）/ `kdc`（结构化表示）；默认不传。docx/doc/pdf/wps/otl（markdown|plain|kdc）；ppt/pptx（markdown|kdc）；xlsx/xls 仅 format=markdown 走整文件抽取，其它值或不传则读取表格选区",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "sheet_id": {
          "description": "xlsx/ksheet/dbt 选表 ID（数字）；优先级高于 sheet_name。xlsx/xls 在 format=markdown 时不生效",
          "type": "number"
        },
        "sheet_name": {
          "description": "xlsx/ksheet/dbt 选表名称；与 sheet_id 同传时优先 sheet_id。xlsx/xls 在 format=markdown 时不生效",
          "type": "string"
        },
        "sheet_range": {
          "description": "xlsx/ksheet 选区，均为 0-based；不传时走默认首 500 行 × 52 列并截断。xlsx/xls 在 format=markdown 时不生效",
          "type": "object",
          "properties": {
            "col_from": {
              "description": "起始列（0-based）",
              "type": "number"
            },
            "col_to": {
              "description": "结束列（0-based，inclusive）",
              "type": "number"
            },
            "row_from": {
              "description": "起始行（0-based）",
              "type": "number"
            },
            "row_to": {
              "description": "结束行（0-based，inclusive）",
              "type": "number"
            }
          }
        },
        "task_id": {
          "description": "docx/doc/wps/pdf/otl（format=markdown|plain）、ppt/pptx（format=markdown|kdc）、xlsx/xls（format=markdown）续跑：上次响应 data.task_id",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "move_file",
    "description": "批量移动文件(夹)。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "驱动盘 ID",
          "type": "string"
        },
        "dst_drive_id": {
          "description": "目标盘 ID",
          "type": "string"
        },
        "dst_parent_id": {
          "description": "目标父目录，根目录 \"0\"",
          "type": "string"
        },
        "file_ids": {
          "description": "文件 ID 列表",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "drive_id",
        "file_ids",
        "dst_drive_id",
        "dst_parent_id"
      ]
    }
  },
  {
    "name": "copy_file",
    "description": "复制文件到指定位置。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "源文件所在驱动盘 ID",
          "type": "string"
        },
        "dst_drive_id": {
          "description": "目标驱动盘 ID",
          "type": "string"
        },
        "dst_parent_id": {
          "description": "目标父目录 ID，根目录为 \"0\"",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "dst_drive_id",
        "dst_parent_id"
      ]
    }
  },
  {
    "name": "rename_file",
    "description": "重命名文件（夹）。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "驱动盘 ID",
          "type": "string"
        },
        "dst_name": {
          "description": "新文件名，须带后缀",
          "type": "string"
        },
        "file_id": {
          "description": "文件（夹）ID",
          "type": "string"
        }
      },
      "required": [
        "file_id",
        "dst_name"
      ]
    }
  },
  {
    "name": "list_latest_items",
    "description": "获取最近访问的文档列表。",
    "parameters": {
      "type": "object",
      "properties": {
        "exclude_creators": {
          "description": "排除的创建者 ID，逗号分隔",
          "type": "string"
        },
        "exclude_exts": {
          "description": "排除的文件后缀，逗号分隔",
          "type": "string"
        },
        "include_creators": {
          "description": "包含的创建者 ID，逗号分隔",
          "type": "string"
        },
        "include_exts": {
          "description": "包含的文件后缀，逗号分隔",
          "type": "string"
        },
        "page_size": {
          "description": "分页大小，常用 20，限制在 1–500；超过 500 按 500；小于 1 时按 20",
          "type": "number"
        },
        "page_token": {
          "description": "分页 token",
          "type": "string"
        },
        "with_link": {
          "description": "是否返回分享信息",
          "type": "boolean"
        },
        "with_permission": {
          "description": "是否返回权限信息",
          "type": "boolean"
        }
      }
    }
  },
  {
    "name": "otl.insert_content",
    "description": "向智能文档写入 Markdown 或纯文本内容，可从文档开头插入或在末尾追加。",
    "parameters": {
      "type": "object",
      "properties": {
        "content": {
          "description": "Markdown 或 HTML 内容",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "format": {
          "description": "内容格式：markdown / html，默认 markdown",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "mode": {
          "description": "写入模式：prepend / append / replace；分别表示头插、尾插、整文替换",
          "type": "string"
        },
        "pos": {
          "description": "【已废弃】历史参数：begin / end。未传 mode 时会兼容映射为 prepend / append",
          "type": "string"
        },
        "title": {
          "description": "文档标题，可选",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "content"
      ]
    }
  },
  {
    "name": "otl.convert",
    "description": "将 HTML 或 Markdown 转为可插入的智能文档块结构，适合在正式插入前先生成块内容。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "params": {
          "description": "转换参数对象",
          "type": "object",
          "properties": {}
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "params"
      ]
    }
  },
  {
    "name": "otl.block_query",
    "description": "查询指定块的结构与内容，适合在更新前先读取目标块信息。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "params": {
          "description": "查询参数对象，如 {\"blockIds\": [...]}",
          "type": "object",
          "properties": {}
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "params"
      ]
    }
  },
  {
    "name": "otl.block_insert",
    "description": "向智能文档插入一个或多个块，适合按位置添加段落、列表、表格等结构化内容。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "params": {
          "description": "插入参数对象",
          "type": "object",
          "properties": {}
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "params"
      ]
    }
  },
  {
    "name": "otl.block_update",
    "description": "更新一个或多个已存在的块，适合修改段落、列表、表格等结构化内容。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "params": {
          "description": "更新操作列表，每项为一个更新块对象",
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "params"
      ]
    }
  },
  {
    "name": "otl.block_delete",
    "description": "删除一个或多个块区间，适合按父块和索引范围移除内容。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "params": {
          "description": "删除参数对象",
          "type": "object",
          "properties": {}
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "params"
      ]
    }
  },
  {
    "name": "share_file",
    "description": "开启文件分享。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "云盘 ID",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "opts": {
          "description": "allow_perm_apply, check_code, close_after_expire, expire_period, expire_time",
          "type": "object",
          "properties": {}
        },
        "role_id": {
          "description": "须传 list_drive_roles 返回的 items[].id；不可传预设 code；不支持仅查看（view_only）与可管理（manageable）",
          "type": "string"
        },
        "scope": {
          "description": "anyone / company / users",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "scope"
      ]
    }
  },
  {
    "name": "get_share_info",
    "description": "获取分享链接信息。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "set_collaborator_permissions",
    "description": "批量新增或修改文档协作者权限；授权主体对象已存在时更新授权角色。暂不支持高级权限。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "云盘 ID；传 url/link_id/file_id 时可省略（由定位解析）",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "notify_subject_user": {
          "description": "授权后是否通知被授权用户，默认通知",
          "type": "boolean"
        },
        "overwrite": {
          "description": "是否覆盖子文件，默认 false",
          "type": "boolean"
        },
        "role_id": {
          "description": "授权角色。可传 list_drive_roles 的 items[].code（viewable/view_only/editable/commentable/manageable），或自定义角色的 items[].id",
          "type": "string"
        },
        "subjects": {
          "description": "授权主体对象列表",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "subject_id": {
                "description": "授权主体对象 ID（用户场景即 user_id）",
                "type": "string"
              },
              "subject_type": {
                "description": "授权主体对象类型：user（用户）/ dept（部门）/ company（企业）/ group（团队）",
                "type": "string",
                "enum": [
                  "user",
                  "dept",
                  "company",
                  "group"
                ]
              }
            },
            "required": [
              "subject_type",
              "subject_id"
            ]
          }
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "role_id",
        "subjects"
      ]
    }
  },
  {
    "name": "list_document_collaborators",
    "description": "获取文档最近协作成员（访客）列表，含在线与离线用户。users 可含 offline 状态；total 为过滤前在线用户总数，不等于 users.length。",
    "parameters": {
      "type": "object",
      "properties": {
        "disable_sticky": {
          "description": "是否禁用创建者置顶",
          "type": "boolean"
        },
        "exclude_online": {
          "description": "是否排除在线用户",
          "type": "boolean"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "filter_status": {
          "description": "筛选状态",
          "type": "string"
        },
        "ignore_collaborator_switch": {
          "description": "是否忽略协作者查看开关",
          "type": "boolean"
        },
        "ignore_offline_switch": {
          "description": "是否忽略企业离线访问记录开关",
          "type": "boolean"
        },
        "include_pc": {
          "description": "是否包含 PC 端在线用户",
          "type": "boolean"
        },
        "include_permissions": {
          "description": "权限筛选（AND 语义）",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "limit": {
          "description": "返回条数上限，最大 1000",
          "type": "number"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "limit"
      ]
    }
  },
  {
    "name": "create_document_comment",
    "description": "在云文档中创建全文评论或回复（留言面板）。",
    "parameters": {
      "type": "object",
      "properties": {
        "content": {
          "description": "评论正文，1-10000 字符",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "origin_id": {
          "description": "根评论 ID；回复时必填，与 reply_id 配对",
          "type": "string"
        },
        "reply_id": {
          "description": "被回复的评论 ID；回复根评论时与 origin_id 相同，回复子评论时为该子评论 ID",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "content"
      ]
    }
  },
  {
    "name": "wps.create_empty_document",
    "description": "创建空白在线文字",
    "parameters": {
      "type": "object",
      "properties": {
        "group_id": {
          "description": "团队 gid，默认 0",
          "type": "number"
        },
        "name": {
          "description": "文件名 tname，可选",
          "type": "string"
        },
        "parent_id": {
          "description": "目录 pid，默认 0",
          "type": "number"
        },
        "template_id": {
          "description": "模板 tid，默认 0",
          "type": "number"
        },
        "tname": {
          "description": "与 name 等价，优先于 name",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "wps.read_text",
    "description": "读取在线文字文档的文本内容。action: full_content(全文), page_count(页数), word_count(字数), doc_info(文档信息), paragraph_count(段落数), paragraph(段落内容), paragraph_range(段落位置范围), paragraph_format(段落格式), paragraph_font(段落字体), paragraph_page_number(段落页码), range_content(区间内容), range_font(区间字体)",
    "parameters": {
      "type": "object",
      "properties": {
        "action": {
          "description": "操作类型",
          "type": "string"
        },
        "begin": {
          "description": "起始字符位置，action 为 range* 时必填",
          "type": "number"
        },
        "end": {
          "description": "结束字符位置，action 为 range* 时必填",
          "type": "number"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "paragraph_index": {
          "description": "段落索引，action 为 paragraph* 时必填，从 1 开始",
          "type": "number"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "wps.write_text",
    "description": "在在线文字文档中插入、追加、更新或删除文本。action: insert(在文档末尾追加文本), append_heading(追加标题), delete_all(删除全部内容), paragraph_insert(在段落前后插入), paragraph_heading_insert(在段落前后插入标题), paragraph_update(更新段落内容), paragraph_delete(删除段落内容), range_insert(在区间插入), range_update(更新区间内容), range_delete(删除区间内容)",
    "parameters": {
      "type": "object",
      "properties": {
        "action": {
          "description": "操作类型",
          "type": "string"
        },
        "alignment": {
          "description": "制表位对齐方式（action=set_tab_stops；等同 tab_alignment）",
          "type": "number"
        },
        "begin": {
          "description": "区间起始位置",
          "type": "number"
        },
        "border_key": {
          "description": "边框属性名（action=set_borders）：LineStyle | LineWidth | Color",
          "type": "string"
        },
        "border_type": {
          "description": "边框位置 WdBorderIndex（上=-1 左=-2 底=-3 右=-4 横向=-5 纵向=-6 斜下=-7 斜上=-8）",
          "type": "number"
        },
        "border_value": {
          "description": "边框属性值（action=set_borders），须与 border_key 匹配",
          "type": "number"
        },
        "color": {
          "description": "BackgroundPatternColor 的 RGB(BGR) 简写（action=set_shading），勿传 WdColorIndex",
          "type": "number"
        },
        "content": {
          "description": "更新的文本内容（paragraph_update/range_update 时使用）",
          "type": "string"
        },
        "end": {
          "description": "区间结束位置",
          "type": "number"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "heading_level": {
          "description": "WdBuiltinStyle 枚举值（负整数）：-2=标题1, -3=标题2, ..., -10=标题9, -1=正文, -32=页眉, -33=页脚, -30=脚注文本, -63=标题, -75=副标题",
          "type": "number"
        },
        "is_br": {
          "description": "action=insert 时是否追加段落符，默认 false",
          "type": "boolean"
        },
        "leader": {
          "description": "前导符类型（action=set_tab_stops；等同 tab_leader）",
          "type": "number"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "paragraph_index": {
          "description": "段落索引",
          "type": "number"
        },
        "paragraph_position": {
          "description": "段落插入位置：before/after，默认 after",
          "type": "string"
        },
        "position": {
          "description": "制表位位置磅值（action=set_tab_stops；等同 tab_position）",
          "type": "number"
        },
        "shading_key": {
          "description": "底纹属性名（action=set_shading）：BackgroundPatternColor 或 BackgroundPatternColorIndex",
          "type": "string"
        },
        "shading_value": {
          "description": "底纹属性值（action=set_shading），须与 shading_key 匹配",
          "type": "number"
        },
        "text": {
          "description": "要插入的文本内容",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "wps.read_table",
    "description": "查询在线文字文档中的表格信息。action: count(表格数量), dimensions(行列数), cell(单元格内容), row(整行内容), column(整列内容), range(表格范围)",
    "parameters": {
      "type": "object",
      "properties": {
        "action": {
          "description": "查询类型",
          "type": "string"
        },
        "col": {
          "description": "列号",
          "type": "number"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "row": {
          "description": "行号",
          "type": "number"
        },
        "table_index": {
          "description": "表格索引，从 1 开始",
          "type": "number"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "wps.write_table",
    "description": "在在线文字文档中创建或删除表格。action: insert(插入新表格), delete(删除表格), delete_row(删除行), delete_column(删除列), delete_cell_content(清空单元格), delete_all(删除所有表格), insert_row(插入行), insert_column(插入列), paragraph_insert(在段落处插入表格), range_insert(在区间处插入表格)",
    "parameters": {
      "type": "object",
      "properties": {
        "action": {
          "description": "操作类型",
          "type": "string"
        },
        "begin": {
          "description": "区间起始",
          "type": "number"
        },
        "col": {
          "description": "列号",
          "type": "number"
        },
        "cols": {
          "description": "表格列数（action=insert 时）",
          "type": "number"
        },
        "end": {
          "description": "区间结束",
          "type": "number"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "paragraph_index": {
          "description": "段落索引",
          "type": "number"
        },
        "paragraph_position": {
          "description": "段落插入位置：before/after",
          "type": "string"
        },
        "position": {
          "description": "行列插入位置：before/after",
          "type": "string"
        },
        "row": {
          "description": "行号",
          "type": "number"
        },
        "rows": {
          "description": "表格行数（action=insert 时）",
          "type": "number"
        },
        "table_index": {
          "description": "表格索引",
          "type": "number"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "wps.search_replace",
    "description": "在在线文字文档中搜索或替换文本。action: search(搜索), replace(替换)",
    "parameters": {
      "type": "object",
      "properties": {
        "action": {
          "description": "操作类型：search 或 replace",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "find_text": {
          "description": "要查找的文本",
          "type": "string"
        },
        "is_all": {
          "description": "是否全部匹配/替换，默认 true",
          "type": "boolean"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "replace_text": {
          "description": "替换文本（action=replace 时必填）",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "action",
        "find_text"
      ]
    }
  },
  {
    "name": "wps.export",
    "description": "统一导出在线文字文档。format 支持 docx / pdf / ap；其中 pdf / ap 为创建导出任务或导出流程入口。",
    "parameters": {
      "type": "object",
      "properties": {
        "cid": {
          "description": "format=docx 时可选，分享链接 ID",
          "type": "string"
        },
        "client_id": {
          "description": "导出时可选的客户端标识",
          "type": "string"
        },
        "export_modify_password": {
          "description": "format=pdf 时可选，导出 PDF 修改密码",
          "type": "string"
        },
        "export_open_password": {
          "description": "format=pdf 时可选，导出 PDF 打开密码",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "format": {
          "description": "docx / pdf / ap",
          "type": "string"
        },
        "from_page": {
          "description": "format=pdf 时可选，默认 1",
          "type": "number"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "multipage": {
          "description": "format=pdf 时可选，默认 1",
          "type": "number"
        },
        "name": {
          "description": "format=ap 时必填，AP 文稿名称，不含后缀",
          "type": "string"
        },
        "opt_frame": {
          "description": "format=pdf 时可选，默认 true",
          "type": "boolean"
        },
        "password": {
          "description": "format=pdf 时可选，源文档密码",
          "type": "string"
        },
        "store_type": {
          "description": "format=pdf 时可选，如 ks3、cloud",
          "type": "string"
        },
        "to_page": {
          "description": "format=pdf 时可选，默认 9999",
          "type": "number"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "with_checksums": {
          "description": "format=docx 时可选，校验算法列表，如 md5,sha256",
          "type": "string"
        }
      },
      "required": [
        "format"
      ]
    }
  },
  {
    "name": "sheet.get_sheets_info",
    "description": "获取当前表格文档下所有工作表基本信息。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "sheet.get_range_data",
    "description": "获取指定工作表中某个矩形选区内的单元格数据。使用 worksheet_id 指定工作表。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "range": {
          "description": "选区范围",
          "type": "object",
          "properties": {
            "colFrom": {
              "description": "起始列(0-based)",
              "type": "number"
            },
            "colTo": {
              "description": "结束列",
              "type": "number"
            },
            "rowFrom": {
              "description": "起始行(0-based)",
              "type": "number"
            },
            "rowTo": {
              "description": "结束行",
              "type": "number"
            }
          }
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_id": {
          "description": "工作表 ID",
          "type": "number"
        }
      },
      "required": [
        "range"
      ]
    }
  },
  {
    "name": "sheet.update_range_data",
    "description": "批量更新单元格选区数据，支持写入公式、设置格式、合并单元格、写入图片。使用 worksheet_id 指定工作表。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "rangeData": {
          "description": "操作列表",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "cellPicInfo": {
                "description": "opType=picture 时",
                "type": "object"
              },
              "colFrom": {
                "description": "起始列(0-based)",
                "type": "number"
              },
              "colTo": {
                "description": "结束列",
                "type": "number"
              },
              "formula": {
                "description": "opType=formula 时",
                "type": "string"
              },
              "opType": {
                "description": "操作类型",
                "type": "string",
                "enum": [
                  "formula",
                  "format",
                  "merge",
                  "picture"
                ]
              },
              "rowFrom": {
                "description": "起始行(0-based)",
                "type": "number"
              },
              "rowTo": {
                "description": "结束行",
                "type": "number"
              },
              "type": {
                "description": "opType=merge 时如 MergeCenter",
                "type": "string"
              },
              "xf": {
                "description": "opType=format 时格式",
                "type": "object"
              }
            },
            "required": [
              "opType",
              "rowFrom",
              "rowTo",
              "colFrom",
              "colTo"
            ]
          }
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_id": {
          "description": "工作表 ID",
          "type": "number"
        }
      },
      "required": [
        "rangeData"
      ]
    }
  },
  {
    "name": "sheet.range_data_batch_update",
    "description": "批量更新单元格选区数据，可插入图片",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "range_data": {
          "description": "单元格操作数组,每项含必填字段 col_from/col_to/row_from/row_to/op_type 及其他非必填字段",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "op_type": {
                "description": "操作类型",
                "type": "string",
                "enum": [
                  "cell_operation_type_formula",
                  "cell_operation_type_picture",
                  "cell_operation_type_format",
                  "cell_operation_type_merge"
                ]
              }
            },
            "required": [
              "op_type"
            ]
          }
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_id": {
          "description": "工作表 ID",
          "type": "number"
        }
      },
      "required": [
        "worksheet_id",
        "range_data"
      ]
    }
  },
  {
    "name": "sheet.add_sheet",
    "description": "在指定表格文件中新增工作表；before、after、end 三选一。before/after 内的 worksheet_id 与 sheetId 二选一。",
    "parameters": {
      "type": "object",
      "properties": {
        "after": {
          "description": "插入到某 sheet 之后",
          "type": "object",
          "properties": {
            "sheetId": {
              "description": "工作表 ID（旧版兼容，与 worksheet_id 二选一）",
              "type": "number"
            },
            "worksheet_id": {
              "description": "工作表 ID（优先，与 sheetId 二选一）",
              "type": "number"
            }
          }
        },
        "before": {
          "description": "插入到某 sheet 之前",
          "type": "object",
          "properties": {
            "sheetId": {
              "description": "工作表 ID（旧版兼容，与 worksheet_id 二选一）",
              "type": "number"
            },
            "worksheet_id": {
              "description": "工作表 ID（优先，与 sheetId 二选一）",
              "type": "number"
            }
          }
        },
        "count": {
          "description": "新增数量，默认 1",
          "type": "number"
        },
        "defColWidth": {
          "description": "默认列宽（单位：缇）",
          "type": "number"
        },
        "end": {
          "description": "是否插入到末尾；传入时必须为 true",
          "type": "boolean"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "name": {
          "description": "工作表名称",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "sheet.delete_sheets",
    "description": "删除工作表",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_ids": {
          "description": "工作表 ID 列表",
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    }
  },
  {
    "name": "sheet.find_range_data",
    "description": "查找单元格",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "filter": {
          "description": "筛选条件",
          "type": "object",
          "properties": {}
        },
        "ignore_hidden_cell": {
          "description": "为true时忽略隐藏的单元格，默认为false",
          "type": "boolean"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "option_cols": {
          "description": "想获取的选项坐标，相对于range",
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "page": {
          "description": "分页，可选",
          "type": "object",
          "properties": {}
        },
        "range": {
          "description": "筛选的区域",
          "type": "object",
          "properties": {}
        },
        "show_total": {
          "description": "是否显示总数 默认为false",
          "type": "boolean"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_id": {
          "description": "工作表 ID",
          "type": "number"
        }
      },
      "required": [
        "worksheet_id",
        "filter",
        "range"
      ]
    }
  },
  {
    "name": "sheet.delete_range_data",
    "description": "删除指定工作表的单元格选区数据",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "range_data": {
          "description": "选区范围数组，每项含 col_from/col_to/row_from/row_to",
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "shift_type": {
          "description": "移动方式，默认 shift_up；可选 shift_up / shift_left",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_id": {
          "description": "工作表 ID",
          "type": "number"
        }
      },
      "required": [
        "worksheet_id",
        "range_data"
      ]
    }
  },
  {
    "name": "sheet.insert_rows_cols",
    "description": "在指定工作表中插入行或列。type=row 时需传 row_from/row_to，type=col 时需传 col_from/col_to。",
    "parameters": {
      "type": "object",
      "properties": {
        "col_from": {
          "description": "插入起始列索引（type=col 时必填，0-based）",
          "type": "number"
        },
        "col_to": {
          "description": "插入结束列索引（type=col 时必填）",
          "type": "number"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "row_from": {
          "description": "插入起始行索引（type=row 时必填，0-based）",
          "type": "number"
        },
        "row_to": {
          "description": "插入结束行索引（type=row 时必填）",
          "type": "number"
        },
        "type": {
          "description": "插入类型：row 插入行，col 插入列",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_id": {
          "description": "工作表 ID",
          "type": "number"
        }
      },
      "required": [
        "worksheet_id",
        "type"
      ]
    }
  },
  {
    "name": "sheet.merge_range",
    "description": "合并单元格。across=true 时按行合并（每行内合并，行间不合并）；默认合并为一个单元格。",
    "parameters": {
      "type": "object",
      "properties": {
        "across": {
          "description": "true 时按行合并，每行内合并为一个单元格；false 或不传则整个区域合并为一个单元格",
          "type": "boolean"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "range": {
          "description": "单元格区域，如 A1:C3",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "worksheet_id": {
          "description": "工作表 ID",
          "type": "number"
        }
      },
      "required": [
        "worksheet_id",
        "range"
      ]
    }
  },
  {
    "name": "wpp.create_empty_presentation",
    "description": "新建空白在线演示文稿。",
    "parameters": {
      "type": "object",
      "properties": {
        "group_id": {
          "description": "团队/空间 ID，0 表示默认个人空间",
          "type": "number"
        },
        "name": {
          "description": "文件名（含后缀），不传由系统生成",
          "type": "string"
        },
        "parent_id": {
          "description": "上级目录 ID，0 表示根目录",
          "type": "number"
        },
        "template_id": {
          "description": "模板 ID，空白传 0",
          "type": "number"
        },
        "type": {
          "description": "固定为 wpp，默认 wpp",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "wpp.read_slide",
    "description": "查询演示文稿幻灯片相关信息。action: query_count(幻灯片总数), query_detail(单张幻灯片详情), query_list(幻灯片列表), slides_notes_query(查询幻灯片备注), slides_tags_query(查询幻灯片标签)",
    "parameters": {
      "type": "object",
      "properties": {
        "action": {
          "description": "查询操作",
          "type": "string"
        },
        "body": {
          "description": "完整请求体，优先使用",
          "type": "object",
          "properties": {}
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "name": {
          "description": "标签名，slides_tags_query 按名查询时传入",
          "type": "string"
        },
        "slide_id": {
          "description": "幻灯片 ID，query_detail/notes/tags 时必填",
          "type": "number"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "wpp.write_slide",
    "description": "插入、移动、复制或删除演示文稿幻灯片，以及管理幻灯片标签。action: slides_items_insert(插入空白幻灯片), slides_items_delete(删除幻灯片), update_move(移动幻灯片位置), update_duplicate(复制幻灯片), slides_tags_update(更新幻灯片标签，body.action 为 ADD 或 DELETE)",
    "parameters": {
      "type": "object",
      "properties": {
        "action": {
          "description": "写操作",
          "type": "string"
        },
        "body": {
          "description": "完整请求体，优先使用",
          "type": "object",
          "properties": {}
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "index": {
          "description": "插入位置索引（slides_items_insert）",
          "type": "number"
        },
        "layout": {
          "description": "版式索引（slides_items_insert）",
          "type": "number"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "name": {
          "description": "标签名（slides_tags_update）",
          "type": "string"
        },
        "slide_id": {
          "description": "目标幻灯片 ID",
          "type": "number"
        },
        "to_position": {
          "description": "目标位置（update_move）",
          "type": "number"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "value": {
          "description": "标签值（slides_tags_update ADD 时）",
          "type": "string"
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "wpp.export_pdf",
    "description": "将演示文稿导出为 PDF。创建任务时传 url / link_id / file_id 三选一；已有 task_id 时可继续查询结果。",
    "parameters": {
      "type": "object",
      "properties": {
        "client_id": {
          "description": "客户端标识",
          "type": "string"
        },
        "export_modify_password": {
          "description": "导出 PDF 修改密码",
          "type": "string"
        },
        "export_open_password": {
          "description": "导出 PDF 打开密码",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一（创建任务）",
          "type": "string"
        },
        "format": {
          "description": "创建任务时填 pdf",
          "type": "string"
        },
        "from_page": {
          "description": "起始页，默认 1",
          "type": "number"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一（创建任务）",
          "type": "string"
        },
        "multipage": {
          "description": "默认 1",
          "type": "number"
        },
        "opt_frame": {
          "description": "是否优化帧，默认 true",
          "type": "boolean"
        },
        "password": {
          "description": "源文件密码",
          "type": "string"
        },
        "store_type": {
          "description": "如 ks3",
          "type": "string"
        },
        "task_id": {
          "description": "轮询时必填，与 task_type 配合",
          "type": "string"
        },
        "task_type": {
          "description": "轮询时填 normal_export",
          "type": "string"
        },
        "to_page": {
          "description": "结束页，默认 9999",
          "type": "number"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一（创建任务）",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "pdf.get_pdf_page_count",
    "description": "查询 PDF 文件的总页数。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "pdf.extract_pdf_pages",
    "description": "从 PDF 中提取指定页码范围，生成新的 PDF 文件并返回下载地址。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "ranges": {
          "description": "要提取的页码范围列表，每项含 from 和 to（1-based）",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "from": {
                "description": "起始页（1-based，含）",
                "type": "integer"
              },
              "to": {
                "description": "结束页（1-based，含）",
                "type": "integer"
              }
            },
            "required": [
              "from",
              "to"
            ]
          }
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "ranges"
      ]
    }
  },
  {
    "name": "pdf.convert",
    "description": "将 PDF 转换为 Office 文件（docx/xlsx/pptx），返回转换任务信息。",
    "parameters": {
      "type": "object",
      "properties": {
        "edit_password": {
          "description": "编辑密码，可选",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "file_name": {
          "description": "原文件名（不含扩展名），默认 document",
          "type": "string"
        },
        "is_free_convert": {
          "description": "是否使用免费转换额度，默认 true",
          "type": "boolean"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "messy_repair": {
          "description": "是否开启乱码修复，默认 false",
          "type": "boolean"
        },
        "open_password": {
          "description": "打开密码，可选",
          "type": "string"
        },
        "page_range_from": {
          "description": "起始页码（默认 1）",
          "type": "number"
        },
        "page_range_to": {
          "description": "结束页码（默认 1）",
          "type": "number"
        },
        "to_format": {
          "description": "目标格式：docx、xlsx、pptx",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "to_format"
      ]
    }
  },
  {
    "name": "pdf.convert_query",
    "description": "查询 PDF 转换任务进度，完成后返回结果文件信息。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "fname": {
          "description": "源 PDF 文件名（含 .pdf 后缀），默认 document.pdf",
          "type": "string"
        },
        "jobid": {
          "description": "转换任务 ID",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      },
      "required": [
        "jobid"
      ]
    }
  },
  {
    "name": "dbsheet.get_schema",
    "description": "获取多维表格文档的 Schema 信息，包括所有数据表、字段和视图结构。",
    "parameters": {
      "type": "object",
      "properties": {
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "include_all_record_ids": {
          "description": "是否返回所有记录 ID，默认 false",
          "type": "boolean"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "reserve_no_permission_sheet": {
          "description": "是否保留无权限的表，默认 false",
          "type": "boolean"
        },
        "sheet_id": {
          "description": "指定数据表 ID，不填则返回所有表",
          "type": "number"
        },
        "show_very_hidden": {
          "description": "是否显示深度隐藏的表，默认 true",
          "type": "boolean"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "dbsheet.list_records",
    "description": "分页遍历数据表中的记录，支持按视图过滤、指定返回字段，以及通过 filter 参数实现多字段 AND/OR 组合筛选。响应中 offset 为下一页游标，传入 offset 可继续翻页。",
    "parameters": {
      "type": "object",
      "properties": {
        "fields": {
          "description": "只返回指定字段列表，不填则返回所有字段",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "filter": {
          "description": "筛选条件，含 mode 和 criteria 列表",
          "type": "object",
          "properties": {}
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "link_value": {
          "description": "关联字段值格式：id / value",
          "type": "string"
        },
        "max_records": {
          "description": "最多返回的记录总数",
          "type": "number"
        },
        "offset": {
          "description": "翻页游标，首次传空字符串，后续传响应中的 offset",
          "type": "string"
        },
        "page_size": {
          "description": "每页记录数",
          "type": "number"
        },
        "prefer_id": {
          "description": "是否使用字段 ID 作为 key",
          "type": "boolean"
        },
        "sheet_id": {
          "description": "目标数据表 ID",
          "type": "number"
        },
        "show_fields_info": {
          "description": "是否在响应中返回字段定义信息",
          "type": "boolean"
        },
        "show_record_extra_info": {
          "description": "是否返回记录额外信息",
          "type": "boolean"
        },
        "text_value": {
          "description": "文本值格式：original / display",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "view_id": {
          "description": "按指定视图返回记录",
          "type": "string"
        }
      },
      "required": [
        "sheet_id"
      ]
    }
  },
  {
    "name": "dbsheet.create_records",
    "description": "在指定数据表中批量创建记录，通过字段名称或字段 ID 指定各字段的值。调用前必须先通过 get_schema 确认字段名和字段类型。",
    "parameters": {
      "type": "object",
      "properties": {
        "add_select_item": {
          "description": "是否自动新增不存在的选项，默认 true",
          "type": "boolean"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "link_value": {
          "description": "关联字段值格式：id / all",
          "type": "string"
        },
        "omit_failure": {
          "description": "部分记录创建失败时是否继续",
          "type": "boolean"
        },
        "prefer_id": {
          "description": "是否使用字段 ID 作为 key，默认 false（使用字段名）",
          "type": "boolean"
        },
        "records": {
          "description": "要创建的记录列表，每项含 fields 对象",
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "sheet_id": {
          "description": "目标数据表 ID",
          "type": "number"
        },
        "text_value": {
          "description": "文本值格式：original / text / compound",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "value_prefer_id": {
          "description": "字段值是否使用 ID 表示",
          "type": "boolean"
        }
      },
      "required": [
        "sheet_id",
        "records"
      ]
    }
  },
  {
    "name": "dbsheet.update_records",
    "description": "批量更新数据表中已有记录的字段值，每条记录必须提供记录 ID。",
    "parameters": {
      "type": "object",
      "properties": {
        "add_select_item": {
          "description": "是否自动新增不存在的选项",
          "type": "boolean"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "link_value": {
          "description": "关联字段值格式：id / value",
          "type": "string"
        },
        "omit_failure": {
          "description": "部分记录更新失败时是否继续",
          "type": "boolean"
        },
        "prefer_id": {
          "description": "是否使用字段 ID 作为 key",
          "type": "boolean"
        },
        "records": {
          "description": "要更新的记录列表，每项须含 id 和 fields",
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "sheet_id": {
          "description": "目标数据表 ID",
          "type": "number"
        },
        "text_value": {
          "description": "文本值格式：original / display",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "value_prefer_id": {
          "description": "字段值是否使用 ID 表示",
          "type": "boolean"
        }
      },
      "required": [
        "sheet_id",
        "records"
      ]
    }
  },
  {
    "name": "kwiki.list_knowledge_views",
    "description": "查询个人知识库列表，支持按名称关键字过滤。",
    "parameters": {
      "type": "object",
      "properties": {
        "keyword": {
          "description": "名称关键字，可用于模糊匹配",
          "type": "string"
        },
        "page_size": {
          "description": "每页数量，默认由服务端决定",
          "type": "number"
        },
        "page_token": {
          "description": "翻页 token",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "kwiki.list_items",
    "description": "列出知识库或知识库文件夹下的文件和子文件夹。",
    "parameters": {
      "type": "object",
      "properties": {
        "kuid": {
          "description": "知识库 kuid（通常 0s 开头）或文件夹 kuid（通常 0l 开头）",
          "type": "string"
        }
      },
      "required": [
        "kuid"
      ]
    }
  },
  {
    "name": "list_file_versions",
    "description": "获取云文档文件历史版本列表。",
    "parameters": {
      "type": "object",
      "properties": {
        "drive_id": {
          "description": "云盘 ID",
          "type": "string"
        },
        "file_id": {
          "description": "文件 id；与 url、link_id 三选一",
          "type": "string"
        },
        "link_id": {
          "description": "分享 id；与 url、file_id 三选一",
          "type": "string"
        },
        "page_size": {
          "description": "分页大小，1–500，默认 20；超过 500 按 500",
          "type": "number"
        },
        "page_token": {
          "description": "翻页 token；首次不传，后续传上次响应中的 next_page_token",
          "type": "string"
        },
        "url": {
          "description": "文档 URL；与 link_id、file_id 三选一",
          "type": "string"
        },
        "with_comment": {
          "description": "是否返回版本备注（comment 字段）",
          "type": "boolean"
        },
        "with_ext_attrs": {
          "description": "是否返回版本扩展属性（ext_attrs 字段）",
          "type": "boolean"
        }
      }
    }
  }
];
